<?php

/**
 * Implementation of hook_menu().
 */
function zedcard_menu() {
  $items['zedcard'] = array(
    'title' => t('Zed Card'),
	  'access arguments' => array('access content'), 
    'page callback' => 'zedcard_list',
	  'type' => MENU_CALLBACK,
  );
  $items['zedcard/add'] = array(
    'title' => t('Add to Zed Card'),
	  'access arguments' => array('access content'), 
    'page callback' => 'zedcard_add',
	  'type' => MENU_CALLBACK,
  );
  $items['zedcard/remove'] = array(
    'title' => t('Remove from Zed Card'),
	  'access arguments' => array('access content'), 
    'page callback' => 'zedcard_remove',
	  'type' => MENU_CALLBACK,
  );

  return $items;
}

/*
* ADD to zedcard table
*/
function zedcard_add(){
	if($_POST['nid']){
    global $user;
    $allready = 0;
    $results = db_select('zedcard', 'z')
      ->fields('z', array('nid'))
      ->condition('uid', $user->uid)
      ->execute();
    if ($results) {
      foreach ($results as $key => $result) {
        if ($result->nid == $_POST['nid']) {
          $allready = 1;
          break;
        }
      }
    }
    if ($allready == 0) {
      db_insert('zedcard')
      ->fields(
          array(
            'uid' => $user->uid,
            'nid' => $_POST['nid'],
            'uri' => $_POST['uri']
          )
        )
      ->execute();
      drupal_json_output(array('add' => '<div class="message">' . t('IMAGE WAS ADDED TO ZED CARD') . '</div>'));
    }
	}	
}

/* 
* show zedcard
*/
function zedcard_list(){
  global $user;
  $GLOBALS['conf']['cache'] = FALSE;
  $results = db_select('zedcard', 'z')
    ->fields('z', array('nid'))
    ->condition('uid', $user->uid)
    ->execute();
  if ($results) {
    $output = '<div class="ajax-loader zedcard"></div><ul class="row zedcard">';
    foreach ($results as $key => $result) {
      $node = node_load($result->nid);
      if ($node->field_portfolio_stripe_slider[LANGUAGE_NONE][0]) {
        if ($key == 0) {
          $output .= '<li class="views-row-first">';
        } else {
          $output .= '<li >';
        }
        $image = theme('image_style',
          array(
            'style_name' => 'portfolio_300x380',
            'path' => $node->field_portfolio_stripe_slider[LANGUAGE_NONE][0]['uri'],
            'title' => $node->field_portfolio_stripe_slider[LANGUAGE_NONE][0]['title'],
            'alt' => $node->field_portfolio_stripe_slider[LANGUAGE_NONE][0]['alt'],
            'getsize' =>FALSE
          )
        );
        $output .= l($image, 'node/' . $node->nid, array('html' => TRUE));
        $output .= '<div class="link-remove"><a href="#" class="remove" data-nid="' . $node->nid . '">' . t('Remove from Zed Card') . '</a>'
          '<a href="' . file_create_url($node->field_portfolio_stripe_slider[LANGUAGE_NONE][0]['uri']) . '" class="colorbox">' . t('Highres') . '</a></div></li>';
      }
    }
  }
	if (!isset($result)) {
    $output = '<div class="empty-zedcard">' . t('Your Zed Card is empty.') . '</div>';
  }
	return $output;
}

/*
* remove from zedcard table
*/
function zedcard_remove(){
  if($_POST['nid']){
    global $user;
    db_delete('zedcard')
      ->condition('uid', $user->uid)
      ->condition('nid', $_POST['nid'])
      ->execute();
    $result = db_select('zedcard', 'z')
      ->fields('z', array('nid'))
      ->condition('uid', $user->uid)
      ->execute()->fetchObject();
    if (!$result) {
      drupal_json_output(array('add' => '<div class="empty-zedcard">' . t('Your Zed Card is empty.') . '</div>'));
    }
  }
}